# Autogenerated wrapper script for MAiNGO_jll for x86_64-w64-mingw32-libgfortran5-cxx03
export MAiNGO, MAiNGOcpp, libmaingo_c_api

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MAiNGO")
JLLWrappers.@declare_library_product(libmaingo_c_api, "libmaingo-c-api.dll")
JLLWrappers.@declare_executable_product(MAiNGO)
JLLWrappers.@declare_executable_product(MAiNGOcpp)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmaingo_c_api,
        "bin\\libmaingo-c-api.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MAiNGO,
        "bin\\MAiNGO.exe",
    )

    JLLWrappers.@init_executable_product(
        MAiNGOcpp,
        "bin\\MAiNGOcpp.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
